# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Dump resource files
      run: |
        ./src/scripts/dumpResources.ps1 -DumpPath ./data
      shell: pwsh
    - name: Restore dependencies
      run: dotnet restore src/dotnet/DBN.CountryInfo.sln
    - name: Build
      run: dotnet build --no-restore -c release src/dotnet/DBN.CountryInfo.sln
    - name: Test
      run: dotnet test --no-build -c release --verbosity normal src/dotnet/DBN.CountryInfo.sln
