name: Publish DBN.CountryInfo.nupkg

on:
  workflow_dispatch:

jobs:
  build_solution:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: dump resource files
      run: |
        ./src/scripts/dumpResources.ps1 -NodeJs -BasePath .
      shell: pwsh
    - name: restore dependencies
      run: dotnet restore src/dotnet/DBN.CountryInfo.sln
    - name: pack package
      run: dotnet pack src/dotnet/DBN.CountryInfo/DBN.CountryInfo.csproj -c release -p:NuspecFile=DBN.CountryInfo.nuspec
    - name: publish package
      run: dotnet nuget push src/dotnet/DBN.CountryInfo/bin/release/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
